### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Entity019930** [Toast732/sw_improved_conquest_mode#20]
It may just be my inexperience but;

I can only manually install the addon. I've managed to get the addon editor sliders to show, but upon creating a world i get an error "311: attempt to call a nil value(global 'required')" any way I may resolve? I have not tampered with any files in the addon or the game, and I do have a mod pack installed.

**Comment by Toast732** [comment]
you're probably trying to use the non built script

this here is the built script: https://github.com/Toast732/sw_improved_conquest_mode/blob/majour-updates/Addon/_build/out/release/main.lua

**Comment by Entity019930** [comment]
While I'm at it, to make sure I'm installing the mod correctly, am I supposed to leave all subfolders arranged as is, or is any sort of unpacking necessary? 

Really appreciate the quick response time btw.

**Comment by Toast732** [comment]
you'll need the built main.lua (rename to script.lua)
playlist.xml
and all of the vehicle.xmls

oh, and it should still work fine if you dont remove all of the other stuff, but might as well

**Comment by Entity019930** [comment]
The mod seems to have made progress this time, but error code 7633 pops up. "atempt to index nil value(local  't')" and would your reply mean that the other additional lua files in the subfolders are also unnecessary?

**Comment by Toast732** [comment]
ah, yeah, this version has a few bugs, planning to release a fix tonight.

and yeah, those are for the dev environment.

**Comment by SentyFunBall** [comment]
Chances are inside of `%appdata%/Stormworks/data/missions/ICMFOLDER/`, the contents of the folder ICM is in should look 
 something like this.
![image](https://user-images.githubusercontent.com/57205125/219922215-c9533421-cbba-49e1-9658-f480b7de5887.png)
I think this is all the game cares about anyway. As toast said, the current does have a few issues, but the workshop stable version should be fine.

**Comment by Entity019930** [comment]
Alright, Thanks alot. Your assistance is very much appreciated. Thumbs up.

**Comment by Entity019930** [comment]
It has been resolved
